#!/bin/bash

# source path 
SOURCE_ROOT="../../src" 

# Fortran compiler
#F77="mpiifort"
#F77="ifort"
#F77="gfortran"
F77="flang"
#F77="mpifort"

# C compiler
#CC="mpiicc"
#CC="icc"
#CC="gcc"
CC="clang"
#CC="mpicc"

# pre-processor symbol list 
# (set PPLIST=? to get a list of available symbols)
# NEKCOMM, NEKDLAY, BG, MGRID
#PPLIST="MGRID"


# OPTIONAL SETTINGS
# -----------------

# enable MPI (default true)
IFMPI="false"

# auxilliary files to compile
# NOTE: source files have to located in the same directory as makenek
#       a makefile_usr.inc has to be provided containing the build rules 
#USR="foo.o"

# linking flags
#USR_LFLAGS=""

# generic compiler flags
#G="-mcmodel=large"
#G="-g"

# optimization flags
OPT_FLAGS_STD="-O2"
OPT_FLAGS_MAG="-O2"

###############################################################################
# DONT'T TOUCH WHAT FOLLOWS !!!
###############################################################################
# assign version tag
mver=1
# overwrite source path with optional 2nd argument
if [ -d $2 ] && [ $# -eq 2 ]; then
  SOURCE_ROOT="$2"
  echo "change source code directory to: ", $SOURCE_ROOT
fi
# do some checks and create makefile
source $SOURCE_ROOT/makenek.inc
# compile
make -j4 -f makefile 2>&1 | tee compiler.out
exit 0
